spring:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: myGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      #This config means kafka consumer can deserialize all the classes from this package
      properties:
        spring:
          json:
            trusted:
              packages: '*'

  #Configured topics name
    topic:
      name: wikimedia_recentchange

    datasource:
      url: jdbc:mysql://localhost:3306/springBootKafkaRealWorldProjectDb?createDatabaseIfNotExist=true&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
      username: root
      password: admin

    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          show_sql: true
          use_sql_comments: true
          format_sql: true
      hibernate:
        ddl-auto: update
